FROM python:3.8-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements_streamlit.txt
RUN pip install joblib
RUN pip install protobuf==3.20.0
RUN pip install click==7.1.2
RUN pip install streamlit
RUN pip install xgboost
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py"]